mode: first-match

rules:
  - name: "high-value-kill"
    enabled: true
    priority: 10
    filter:
      zkb_value_min: 1000000000
    actions:
      - type: console
      # Uncomment and set url to send Discord notifications:
      - type: webhook
        args:
          url: "https://discord.com/api/webhooks/1483747598366933086/pWrFA3uCmPOEJjenNoZdI3k3ZC5Rq7N7STdRnNjBbh0ScPkY-9SHEeB_btPCa8uaXoy-"
          template: "default"

  - name: "capital-kill"
    enabled: true
    priority: 20
    filter:
      has_capital: true
    actions:
      - type: console
      - type: webhook
        args:
          url: "https://discord.com/api/webhooks/1483747598366933086/pWrFA3uCmPOEJjenNoZdI3k3ZC5Rq7N7STdRnNjBbh0ScPkY-9SHEeB_btPCa8uaXoy-"
          template: "capital"

  - name: "corp-loss"
    enabled: true
    priority: 30
    filter:
      victim_corporation_id: [98812444]
    actions:
      - type: console
      - type: webhook
        args:
          url: "https://discord.com/api/webhooks/1483747598366933086/pWrFA3uCmPOEJjenNoZdI3k3ZC5Rq7N7STdRnNjBbh0ScPkY-9SHEeB_btPCa8uaXoy-"
          template: "loss"

  - name: "solo-pvp"
    enabled: true
    priority: 40
    filter:
      and:
        - solo: true
        - npc: false
    actions:
      - type: console
      - type: webhook
        args:
          url: "https://discord.com/api/webhooks/1483747598366933086/pWrFA3uCmPOEJjenNoZdI3k3ZC5Rq7N7STdRnNjBbh0ScPkY-9SHEeB_btPCa8uaXoy-"
          template: "loss"

  - name: "jita-trade-hub-kill"
    enabled: true
    priority: 50
    filter:
      and:
        - solar_system_name: ["Jita", "Amarr", "Dodixie", "Rens", "Hek"]
        - zkb_value_min: 500000000
        - npc: false
    actions:
      - type: console
      - type: webhook
        args:
          url: "https://discord.com/api/webhooks/1483747598366933086/pWrFA3uCmPOEJjenNoZdI3k3ZC5Rq7N7STdRnNjBbh0ScPkY-9SHEeB_btPCa8uaXoy-"
          template: "default"

  - name: "all-kills"
    enabled: false
    priority: 100
    filter:
      npc: false
    actions:
      - type: console
